[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
primaryColor = "#2C3E50"         # Deep blue-gray for buttons
backgroundColor = "#F9FAFB"      # Light background
secondaryBackgroundColor = "#E5E7EB"  # Cards or sidebars
textColor = "#111827"            # Dark text
font = "sans serif"              # Other options: "monospace", "serif"
